[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  publish = "dist"
  functions = "dist/functions"
  environment = { NODE_VERSION = "16" }

[context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview.environment]
    NODE_ENV = "production"

[context.branch-deploy.environment]
    NODE_ENV = "production"

[context.next.environment]
    NODE_ENV = "production"




